task: detection
num_classes: 1
num_landmarks: 5
output_dir: ./output/emergency_final
epoches: 10
clip_max_norm: 0.1
log_step: 5
checkpoint_step: 2
sync_bn: false
find_unused_parameters: false
use_amp: false
use_ema: false
model: RTDETR
criterion: SetCriterion
postprocessor: RTDETRPostProcessor
RTDETR:
  backbone: PResNet
  encoder: HybridEncoder
  decoder: RTDETRTransformer
  multi_scale:
  - 640
PResNet:
  depth: 50
  variant: d
  freeze_at: 0
  return_idx:
  - 1
  - 2
  - 3
  num_stages: 4
  freeze_norm: true
  pretrained: true
HybridEncoder:
  in_channels:
  - 512
  - 1024
  - 2048
  feat_strides:
  - 8
  - 16
  - 32
  hidden_dim: 256
  use_encoder_idx:
  - 2
  num_encoder_layers: 1
  nhead: 8
  dim_feedforward: 1024
  dropout: 0.0
  enc_act: gelu
  pe_temperature: 10000
  expansion: 1.0
  depth_mult: 1
  act: silu
  eval_spatial_size:
  - 640
  - 640
RTDETRTransformer:
  in_channels:
  - 512
  - 1024
  - 2048
  feat_channels:
  - 512
  - 1024
  - 2048
  feat_strides:
  - 8
  - 16
  - 32
  hidden_dim: 256
  num_levels: 3
  num_queries: 300
  num_decoder_layers: 6
  num_denoising: 50
  eval_idx: -1
  eval_spatial_size:
  - 640
  - 640
use_focal_loss: true
RTDETRPostProcessor:
  num_top_queries: 300
SetCriterion:
  weight_dict:
    loss_vfl: 1.0
    loss_bbox: 5.0
    loss_giou: 2.0
  losses:
  - vfl
  - boxes
  alpha: 0.75
  gamma: 2.0
  matcher:
    type: HungarianMatcher
    weight_dict:
      cost_class: 2
      cost_bbox: 5
      cost_giou: 2
    alpha: 0.25
    gamma: 2.0
optimizer:
  type: AdamW
  lr: 0.0001
  betas:
  - 0.9
  - 0.999
  weight_decay: 0.0001
lr_scheduler:
  type: MultiStepLR
  milestones:
  - 8
  gamma: 0.1
train_dataloader:
  type: DataLoader
  dataset:
    type: FaceLandmarkDataset
    img_folder: ./dataset/faces/train/images/
    ann_file: ./dataset/faces/train/annotations.json
    num_landmarks: 5
    transforms:
      type: ComposeFaceLandmark
      ops:
      - type: Resize
        size:
        - 640
        - 640
      - type: ToImageTensor
      - type: ConvertDtype
      - type: ConvertBox
        out_fmt: cxcywh
        normalize: true
  shuffle: true
  batch_size: 1
  num_workers: 0
  drop_last: false
  collate_fn: default_collate_fn
val_dataloader:
  type: DataLoader
  dataset:
    type: FaceLandmarkDataset
    img_folder: ./dataset/faces/val/images/
    ann_file: ./dataset/faces/val/annotations.json
    num_landmarks: 5
    transforms:
      type: ComposeFaceLandmark
      ops:
      - type: Resize
        size:
        - 640
        - 640
      - type: ToImageTensor
      - type: ConvertDtype
      - type: ConvertBox
        out_fmt: cxcywh
        normalize: true
  shuffle: false
  batch_size: 1
  num_workers: 0
  drop_last: false
  collate_fn: default_collate_fn
