# configs/rtdetr/include/dataloader_face.yml

train_dataloader: 
  dataset: 
    transforms:
      ops:
        - {type: RandomPhotometricDistort, p: 0.5}
        - {type: RandomHorizontalFlip, p: 0.5}
        - {type: Resize, size: [640, 640]}
        - {type: ToImageTensor}
        - {type: ConvertDtype}
        - {type: SanitizeBoundingBox, min_size: 1}
        - {type: ConvertBox, out_fmt: 'cxcywh', normalize: True}
        - {type: SanitizeLandmarks, min_val: 0.0, max_val: 1.0}  # ✅ Add this
  shuffle: True
  batch_size: 16
  num_workers: 4
  collate_fn: default_collate_fn

val_dataloader:
  dataset: 
    transforms:
      ops: 
        - {type: Resize, size: [640, 640]}
        - {type: ToImageTensor}
        - {type: ConvertDtype}
        - {type: ConvertBox, out_fmt: 'cxcywh', normalize: True}
        - {type: SanitizeLandmarks, min_val: 0.0, max_val: 1.0}  # ✅ Add this
  shuffle: False
  batch_size: 8
  num_workers: 4
  collate_fn: default_collate_fn