# configs/rtdetr/include/rtdetr_face_landmark_fixed.yml
task: detection

model: RTDETR
criterion: PolarLandmarkCriterion
postprocessor: RTDETRFacePostProcessor

# Model configuration
RTDETR:
  backbone: PResNet
  encoder: HybridEncoder
  decoder: RTDETRTransformerPolarLandmark
  multi_scale: [640]  # ✅ ใช้ fixed size แทน multi-scale

# Backbone configuration  
PResNet:
  depth: 50
  variant: d
  freeze_at: 0
  return_idx: [1, 2, 3]      # channels → [512, 1024, 2048]
  num_stages: 4
  freeze_norm: True
  pretrained: True

# Fixed Encoder configuration
HybridEncoder:
  in_channels: [512, 1024, 2048]
  feat_strides: [8, 16, 32]  # ✅ แก้ให้ตรงกับ PResNet output
  hidden_dim: 256 
  use_encoder_idx: [2]
  num_encoder_layers: 1
  nhead: 8
  dim_feedforward: 1024
  dropout: 0.
  enc_act: 'gelu'
  pe_temperature: 10000
  expansion: 1.0
  depth_mult: 1
  act: 'silu'
  eval_spatial_size: [640, 640]  # ✅ Fixed evaluation size

# Decoder configuration with polar landmark
RTDETRTransformerPolarLandmark:
  in_channels: [512, 1024, 2048]  # ✅ เพิ่ม in_channels
  feat_channels: [512, 1024, 2048]   # ✅ output จาก encoder
  feat_strides: [8, 16, 32]
  hidden_dim: 256
  num_levels: 3
  num_queries: 300
  num_decoder_layers: 6
  num_denoising: 0       # ✅ disable denoising ก่อน
  eval_idx: -1
  eval_spatial_size: [640, 640]
  num_classes: 1
  num_landmarks: 5
  num_orientations: 8
  heatmap_size: 64
  landmark_loss_weight: 5.0

# Loss configuration
use_focal_loss: True
num_landmarks: 5
num_orientations: 8
heatmap_size: 64

# Post-processor configuration
RTDETRFacePostProcessor:
  num_top_queries: 300
  num_classes: 1
  num_landmarks: 5

# Criterion configuration
PolarLandmarkCriterion:
  num_classes: 1
  num_landmarks: 5
  num_orientations: 8
  heatmap_size: 64
  heatmap_sigma: 2.0
  heatmap_loss_type: 'focal'
  
  weight_dict: {
    loss_vfl: 1.0,
    loss_bbox: 5.0,
    loss_giou: 2.0,
    loss_landmarks: 5.0,
    loss_heatmap: 2.0,
    loss_orientation: 1.0,
    loss_radius: 1.0
  }

  losses: ['vfl', 'boxes', 'landmarks']  # ✅ ต้องมีบรรทัดนี้
  alpha: 0.75
  gamma: 2.0

  matcher:
    type: HungarianMatcher
    weight_dict: { cost_class: 2, cost_bbox: 5, cost_giou: 2 }
    alpha: 0.25
    gamma: 2.0