__include__: [
  '../dataset/face_landmark_detection.yml',
  '../runtime.yml',
  './include/dataloader_face.yml',
  './include/optimizer_face_improved.yml',
  './include/rtdetr_face_landmark.yml',
]

output_dir: ./output/rtdetr_r50vd_face_landmark_v2

# Override some settings for face detection
epoches: 150
checkpoint_step: 5
log_step: 50

# Specific settings for face detection
num_classes: 1  # Only face class
num_landmarks: 5  # 5-point landmarks

# Enable AMP for faster training
use_amp: True

# Tuning from COCO pretrained model
tuning: https://github.com/lyuwenyu/storage/releases/download/v0.1/rtdetr_r50vd_6x_coco_from_paddle.pth
